FUNC_CALL_SUCCESS_CODE = 0000

REDIS_KEY_NOT_FOUND_CODE = 1000
REDIS_KEY_NOT_FOUND_MSG = 'Key not found'

HTTP_REQ_IS_NOT_JSON_CODE = 2000
HTTP_REQ_IS_NOT_JSON = "HTTP request message is not JSON"
HTTP_REQ_PARAMS_MISSING_CODE = 2001
HTTP_REQ_PARAMS_MISSING = "`{param_name}` is missing"
HTTP_REQ_INVALID_PARAM_VALUE_CODE = 2002
HTTP_REQ_INVALID_PARAM_VALUE = "Invalid value"
HTTP_REQ_UNAUTH_CODE = 2003
HTTP_REQ_UNAUTH = "Unauthorize"
HTTP_REQ_NOT_FOUND_CODE = 2004
HTTP_REQ_NOT_FOUND = "Not found"

KEX_INVALID_PUBKEY_CODE = 3000
KEX_INVALID_PUBKEY = "Invalid public key"
KEX_INVALID_DER_CODE = 3001
KEX_INVALID_DER = "Invalid DER structure"
KEX_INVALID_ALG_CODE = 3002
KEX_INVALID_ALG = "Invalid Algorithm"
KEX_GEN_KID_FAILED_CODE = 3003
KEX_GEN_KID_FAILED = "KID generation is failed"
KEX_GEN_INVALID_KID_CODE = 3004
KEX_GEN_INVALID_KID = "Invalid KID"
KEX_GEN_FAILED_CODE = 3005
KEX_GEN_FAILED = "Key agreement failed"

CERT_GET_URL_ERROR_CODE = 4000
CERT_GET_URL_ERROR = "Retrieving trusted URLs is failed"

PLAYFAB_ERROR_CODE = 5000
PLAYFAB_ERROR = "PlayFab error"
PLAYFAB_GET_BALANCE_ERROR_CODE = 5001
PLAYFAB_GET_BALANCE_ERROR = "Cannot get balance from PlayFab"
PLAYFAB_ITEM_EXISTS_CODE = 5002
PLAYFAB_ITEM_EXISTS = "The item exists"
PLAYFAB_ITEM_DOES_NOT_EXIST_CODE = 5003
PLAYFAB_ITEM_DOES_NOT_EXIST = "The item does not exist"
PLAYFAB_GET_ITEM_PRICE_ERROR_CODE = 5004
PLAYFAB_GET_ITEM_PRICE_ERROR = "The item price cannot be retrieved"
PLAYFAB_INSUFFICIENT_FUND_CODE = 5005
PLAYFAB_INSUFFICIENT_FUND = "Insufficient fund"
PLAYFAB_GRANT_ITEM_FAIL_CODE = 5006
PLAYFAB_GRANT_ITEM_FAIL = "Grant an item failed"
PLAYFAB_REVOKE_ITEM_FAIL_CODE = 5007
PLAYFAB_REVOKE_ITEM_FAIL = "Revoke an item failed"
PLAYFAB_GET_PLAYFAB_ID_ERROR_CODE = 5008
PLAYFAB_GET_PLAYFAB_ID_ERROR = "Cannot get PlayFab ID"
PLAYFAB_GET_CATALOG_ERROR_CODE = 5009
PLAYFAB_GET_CATALOG_ERROR = "Cannot get items or no item in the store"

UNKNOWN_ERROR_CODE = 9999
UNKNOWN_ERROR = "Unknown error"

# Logging message
FUNC_CALL_LOG = "Function: {function_name} \nRequest body: {json_body}"